services:
  - type: web
    name: chalkida-hair-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        value: "803113966"
      - key: GEMINI_API_KEY
        value: "AIzaSyC2KkxvmrBKkCWSMXZ2r_MAXYyIh4tySnM"
      - key: DB_URL
        sync: false
